apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apple
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/my-cluster/apple
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-flux-repo
  targetNamespace: apple
