apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: my-flux-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/sonetpy/my-flux-repo
  ref:
    branch: main
