apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: hello-world
    repo: file://../../../helm-charts/hello-world
    version: 0.1.0
    releaseName: hello-world
    namespace: default
