apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-world-prod
  namespace: morgan-prod
spec:
  interval: 5m
  chart:
    spec:
      chart: ../../../../helm-charts/hello-world
      sourceRef:
        kind: GitRepository
        name: my-flux-repo
  values:
    replicaCount: 1
